### ISSUE TITLE
pics

### ISSUE THREAD

**Issue by bugdie4k** [bugdie4k/configs#1]
paste screenshots here

**Comment by fedorough** [comment]
![emacs](https://cloud.githubusercontent.com/assets/22116479/24926148/415354e8-1f03-11e7-964a-a300aef2f35d.png)
![mc](https://cloud.githubusercontent.com/assets/22116479/24926149/4153abbe-1f03-11e7-9a2b-abce16785c2e.png)
![prompt](https://cloud.githubusercontent.com/assets/22116479/24926150/41540082-1f03-11e7-949c-08025aa3b491.png)

**Comment by fedorough** [comment]
update mc and bash screenshots

![image](https://cloud.githubusercontent.com/assets/22116479/25579979/681d5dda-2e85-11e7-8f55-3899c48a745d.png)

![image](https://cloud.githubusercontent.com/assets/22116479/25580020/d6ee3770-2e85-11e7-8c2f-1a3ca24c0a13.png)
